### ISSUE TITLE
TypeError: Row argument 1 must be Cursor, not Cursor

### ISSUE THREAD

**Issue by niki-sp** [libsql/libsql-client-py#18]
When using existing sqlite3 database i get

```
Traceback (most recent call last):
  File "e.py", line 81, in __getitem__
    r = self._cursor.fetchone()
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "~/.local/lib/python3.11/site-packages/libsql_client/dbapi2/types.py", line 845, in __init__
    raise TypeError(msg)
TypeError: Row argument 1 must be Cursor, not Cursor
```

Removing issubclass(cur_tp, Cursor) check seems to restore normal operation

**Comment by niki-sp** [comment]
Same error with full names:
`TypeError: Row argument 1 must be <class 'libsql_client.dbapi2.types.Cursor'>, not <class 'sqlite3.Cursor'>`
